### ISSUE TITLE
Please clarify the license

### ISSUE THREAD

**Issue by voxik** [ruby/fileutils#114]
The license file is BSD-2-Clause license, the readme says _The gem is available as open source under the terms of the 2-Clause BSD License._, but the [gemspec](https://github.com/ruby/fileutils/blob/577fd38f15f74ec95969e379607b1ec457d61203/fileutils.gemspec#L26) specifies Ruby OR BSD-2-Clause. So is the .gemspec wrong or the other places?

**Comment by hsbt** [comment]
Fixed at https://github.com/ruby/fileutils/commit/9e32a88573da53e3dd991669fc3d20d72d0137ae
