### ISSUE TITLE
JRuby has modifications to fileutils

### ISSUE THREAD

**Issue by headius** [ruby/fileutils#17]
The version of fileutils.rb in JRuby differs from MRI in a few JRuby-specific ways. We need to incorporate those changes into the fileutils gem, either as a separate file, branched logic, or a completely separate -java gem (in rough order of preference).

We realized this could be an issue while investigating bundler/bundler#6532. Bundler is now vendoring a copy of fileutils, and their copy also did not reflect our JRuby-specific logic. However they isolate that vendored copy into a separate namespace, so it should not affect normal use of fileutils.

**Comment by headius** [comment]
Ok so the changes may not be a major issue. There appears to be only one diff left:

https://github.com/ruby/ruby/compare/ruby_2_5...jruby:jruby-ruby_2_5_0#diff-08dc84a402724fc771f40b6bddddc546

This logic exists because Java APIs do not allow opening a directory as a file. Normally JRuby (9.2+) does support this via an actual native file descriptor call. However in environments where our native library access is disabled, we will be unable to support this call. I believe we should have a failover here that rescues EISDIR and falls back on the logic that does not attempt to open the directory as a file.

**Comment by headius** [comment]
Fixed by #18.

**Comment by hsbt** [comment]
@headius I was very happy to merge JRuby local patches into CRuby stdlib. You know we have many stdlib as rubygems on https://github.com/ruby. Please submit a JRuby patch contained test code to them. Thanks!
