### ISSUE TITLE
Fileutils 7.0 yanked from rubygems

### ISSUE THREAD

**Issue by aluhrman** [ruby/fileutils#2]
Hi,
I appreciate you updating the fileutils code-base and look forward to using the new version. I believe yanking 7.0 from rubygems was a bit premature, however. Until Ruby 2.5 is available more readily (especially in the official docker images) I would greatly appreciate it if you could reinstate version 7.0 or lower the build requirements if possible. Thanks!

**Comment by hsbt** [comment]
We have no plan to release/re-register old version like fileutils-0.7. It's completely different implementation of the standard library.

You do not need to use fileutils-0.7. fileutils is the standard library for Ruby 2.3 and 2.4. You can use it without `gem install fileutils`.
