### ISSUE TITLE
FileUtils.cp_r with :preserve does not preserve timestamp

### ISSUE THREAD

**Issue by mame** [ruby/fileutils#21]
See https://bugs.ruby-lang.org/issues/5419 in detail.

**Comment by knu** [comment]
If this is the case, there should be another problem that contents of an unwritable directory cannot be copied.

**Comment by jeremyevans** [comment]
This appears to have been fixed in 2013 in 789285ab88e7579a0986add02c1753c74eb0bb3e by @mame.  If you think it is still an issue, please submit a pull request with a failing spec and I will look into fixing it.
