### ISSUE TITLE
fl -> method required to see the list of files and folders  read 

### ISSUE THREAD

**Issue by rsurendraidexcel** [ruby/fileutils#46]
fl -> Folder list to see the file  method not available .. linux is  ls  and window dir    both diferent command , my point  fl -> folder list to see the all  folder list file or sub folder if provide open similar to ls and dir command

**Comment by jeremyevans** [comment]
I think this is a feature request to add `FileUtils.fl`.  Unfortunately, that doesn't fit the purpose of FileUtils, which is file/folder manipulation, not discovery.  So I'm going to reject this feature request. If you want to see all files/folders for a directory tree, you can use `Find.find('/path/to/dir').to_a` (this is from the `find` library in stdlib).
