### ISSUE TITLE
I can't install fileutils

### ISSUE THREAD

**Issue by sasatefa2009** [ruby/fileutils#8]
i get this error when attempting to install fileutils using "gem install fileutils"

```
root@kali:~# gem install fileutils
Fetching: fileutils-0.7.2.gem (100%)
ERROR:  Error installing fileutils:
	fileutils requires Ruby version >= 2.5.0dev.

```

**Comment by hsbt** [comment]
see https://github.com/ruby/fileutils/issues/7#issuecomment-318940162

You don't need to install fileutils on stable ruby versions.

**Comment by sasatefa2009** [comment]
@hsbt Do you mean it's preinstalled ?

**Comment by hsbt** [comment]
@sasatefa2009 Yes. It's standard library of the Ruby language.
